---
- name: Enroll & deploy TLS cert from Venafi as a Service
  hosts: webservers
  become: true
  vars:
    # injected via custom credential or set in extra_vars at run time
    venafi_api_key: "{{ venafi_api_key | default(lookup('env','VENAFI_APIKEY'), true) }}"
    venafi_zone:    "{{ venafi_zone    | default('MyApp\\Default') }}"

    # certificate request parameters
    common_name: "www.example.com"
    dns_sans:
      - "www.example.com"
      - "example.com"
    key_type: "rsa"
    key_length: 2048
    cert_dest_path: "/etc/pki/tls/certs/www.example.com.crt"
    key_dest_path:  "/etc/pki/tls/private/www.example.com.key"
    chain_dest_path: "/etc/pki/tls/certs/www.example.com.chain.crt"
    restart_handler: "restart nginx"

  roles:
    - role: venafi.machine_identity.certificate
      vars:
        provider: vaas              # tell the role we're using Venafi as a Service
        api_key: "{{ venafi_api_key }}"
        zone: "{{ venafi_zone }}"
        common_name: "{{ common_name }}"
        dns_subject_alt_names: "{{ dns_sans }}"
        key_type: "{{ key_type }}"
        key_length: "{{ key_length }}"
        certificate_path: "{{ cert_dest_path }}"
        privatekey_path:  "{{ key_dest_path }}"
        chain_path:       "{{ chain_dest_path }}"
        owner: root
        group: root
        mode: '0640'
        # Optional: service hook
        notify_service: "{{ restart_handler }}"
