---
- name: Renew Venfi Cloud Certificates
  hosts: "{{ target_hosts }}"
  gather_facts: false
  vars:
    validity_days: 90
    before_expired_hours: "{{ validity_check * 24 }}"
    validity_hours: "{{ validity_days * 24 }}"

  pre_tasks:
    - debug: 
        msg: "before_epxired_hours: {{ before_expired_hours }} and validity_hours: {{ validity_hours }}"

  roles:
    - role: "venafi.machine_identity.certificate"
      # Provider: 'vaas' (Venafi Cloud) or 'tpp'
      certificate_provider: "vaas"
      common_name: "{{ inventory_hostname }}"
      token: "{{ venafi_api_key }}"
      # If your collection uses API keys (older style), use this instead and remove access_token:
      # certificate_api_key: "{{ venafi_api_key }}"

      # REQUIRED for both VaaS and TPP
      zone: 'AAP25DemoCrt\Default'   # currently defined in credentials.yml (not here) | format: Application\IssuingTemplate (note the backslash)
      # ^ In YAML, a single backslash is fine when inside quotes. Double backslash is also safe.
      certificate_common_name: "{{ inventory_hostname}}"
      certificate_cert_dir: "/tmp/ansible/etc/ssl/{{ certificate_common_name }}"
      certificate_cert_path: "{{ certificate_cert_dir }}/{{ certificate_common_name }}.pem"
      certificate_chain_path: "{{ certificate_cert_dir }}/{{ certificate_common_name }}.chain.pem"
      certificate_privatekey_path: "{{ certificate_cert_dir }}/{{ certificate_common_name }}.key"
      certificate_csr_path: "{{ certificate_cert_dir }}/{{ certificate_common_name }}.csr"

      certificate_csr_origin: local
      certificate_privatekey_reuse: false
      certificate_privatekey_type: RSA
      certificate_privatekey_size: 2048

      # Where to execute venafi_certificate module. If set to false, certificate will be
      # created on ansible master host and then copied to the remote server.
      certificate_remote_execution: false
      # Remote location where to place the certificate.
      certificate_remote_cert_dir: "/etc/ssl"
      certificate_remote_cert_path: "{{ certificate_remote_cert_dir }}/{{ certificate_common_name }}.pem"
      certificate_remote_chain_path: "{{ certificate_remote_cert_dir }}/{{ certificate_common_name }}.chain.pem"
      certificate_remote_privatekey_path: "{{ certificate_remote_cert_dir }}/{{ certificate_common_name }}.key"
      # Set to false if you don't want to copy private key to remote location.
      certificate_copy_private_key_to_remote: true
      certificate_before_expired_hours: "{{ valdity_check * 24 }}" #validity_check passed from survey
      certificate_validity_hours: "{{ valdiity_days * 24 }}" #validity_days passed from survey