---
- name: Retire recently renewed certificates
  hosts: localhost

  vars:
    vaas_api_key: "{{ venafi_api_key }}"   # or inject via AAP credential as a variable
    tenant_base_url: "https://eval-85300634.venafi.cloud" # your tenant base
    global_api_url:  "https://api.venafi.cloud"

  tasks:
    - name: Retire certificate in Venafi Cloud
      ansible.builtin.uri:
        url: "https://api.venafi.cloud/outagedetection/v1/certificates/retirement"
        method: POST
        headers:
          accept: "application/json"
          content-type: "application/json"
          tppl-api-key: "{{ vaas_api_key }}"
        body_format: json
        body:
          certificateIds: "{{ retire_certs }}" 
        return_content: true
        status_code: 200
      register: retire_response
    
    - name: Show retire response
      ansible.builtin.debug:
        var: retire_response.json