---
- name: Rewnew Venafi Cloud certificates
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cert_list: "{{ refresh_certificates }}"
    validity_days: 23
    vaas_api_key: "{{ venafi_api_key }}"   # or inject via AAP credential as a variable
    tenant_base_url: "https://eval-85300634.venafi.cloud" # your tenant base
    global_api_url:  "https://api.venafi.cloud"

  tasks:
    - name: Debug cert_list
      ansible.builtin.debug:
        var: cert_list

    - name: Renew Certificates
      ansible.builtin.uri:
        url: "https://api.venafi.cloud/outagedetection/v1/applications?ownerDetails=false&ownershipCheck=false&issuingTemplateAssigned=false&ownershipTree=false"
        method: POST
        headers:
          accept: "application/json"
          content-type: "application/json"
          tppl-api-key: "{{ vaas_api_key | default('REDACT_ME') }}"
        body:
          csrAttributes:
            keyTypeParameters:
              keyCurve: "P256"
              keyType: "RSA"
              keyLength: 2048
            commonName: "{{ item.certificateName }}"
          isVaaSGenerated: true
          #applicationId: "{{ item.applicationIds[0] }}"
          #certificateIssuingTemplateId: "{{ item.certificateIssuingTemplateId }}"
          existingCertificateId": "{{ item.instances[0].certificateId }}"
          validityPeriod: P{{ validity_days }}D
        body_format: json
        return_content: true
        status_code: 200,201
      loop: "{{ cert_list }}"
      register: cert_request_response

    - name: Debug cert_request_response
      ansible.builtin.debug:
        var: cert_request_response


#curl --request POST \
#     --url https://api.venafi.cloud/outagedetection/v1/certificaterequests \
#     --header 'accept: application/json' \
#     --header 'content-type: application/json' \
#     --header 'tppl-api-key: 7aa4a121-3c3d-455f-9c4b-872a25c455f8' \
#     --data '
#{
#  "csrAttributes": {
#    "keyTypeParameters": {
#      "keyCurve": "P256",
#      "keyType": "RSA",
#      "keyLength": 2048
#    },
#    "commonName": "webserver.mbredeme.com"
#  },
#  "isVaaSGenerated": true,
#  "applicationId": "db56a9b0-7980-11f0-9cc5-31c907dcc2e3",
#  "certificateIssuingTemplateId": "e1d81b71-6e54-11f0-b1b4-9323192b9202",
#  "validityPeriod": "P90D",
#  "existingCertificateId": "213447f0-8195-11f0-b07c-fb991628f448"
#}
#'

#    - name: Get Venafi Outage Detection Applications
#      ansible.builtin.uri:
#        url: "https://api.venafi.cloud/outagedetection/v1/applications?ownerDetails=false&ownershipCheck=false&issuingTemplateAssigned=false&ownershipTree=false"
#        method: GET
#        headers:
#          accept: "application/json"
#          content-type: "application/json"
#          tppl-api-key: "{{ vaas_api_key | default('REDACT_ME') }}"
#        body:
#          csrAttributes:
#            keyTypeParameters:
#              keyCurve: "P256"
#              keyType: "RSA"
#              keyLength: 2048
#            commonName: "{{ common_name }}"
#          isVaaSGenerated: true
#          applicationId: "{{ app_id}}"
#          certificateIssuingTemplateId: "{{ issuding_template_id }}"
#          validityPeriod: "P45D"
#        body_format: json
#        return_content: true
#        status_code: 200,201
#      register: cert_request_response