- name: venafi_certificate_fake
  connection: local
  hosts: localhost
  vars:
    common_name_default: 'webserver.example.com'
  tags:
    - fake
  tasks:
  - name: venafi_certificate
    venafi.machine_identity.venafi_certificate:
      #token: "{{ venafi_api_key }}"
      test_mode: true
      common_name: "{{ common_name_default }}"
      #zone: "AAP25DemoCrt\\AAP25DemoCert"
      #alt_name: 'DNS:www.venafi.example,DNS:m.venafi.example'
      cert_path: "/tmp/{{ common_name_default }}.crt"
      csr_origin: "local"
      csr_path: ""
    register: certout
  - name: dump test output
    debug:
      msg: '{{ certout }}'